version: "3"

volumes:
  pg_data:

services:
  postgres:
    image: postgres:11.12-alpine
    restart: unless-stopped
    ports:
      - "5600:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: trove_test
